<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TicketingSystem.Domain\TicketingSystem.Domain.csproj" />
    <ProjectReference Include="..\..\src\TicketingSystem.Application\TicketingSystem.Application.csproj" />
    <ProjectReference Include="..\..\src\TicketingSystem.Infrastructure\TicketingSystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>